# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-14 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200523_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('WA', 'Waiting for Answers'), ('SA', 'Showing Answers')], default='WA', max_length=2),
        ),
    ]
