# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
    ]
