# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200615_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_status',
            field=models.CharField(choices=[('WA', 'Waiting for Answers'), ('SA', 'Showing Answers')], default='WA', max_length=2),
        ),
    ]
