# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200615_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='quiz_id',
        ),
    ]
